In [17]:
import pandas as pd
train = pd.read_csv("Data/train.csv")

# Split into overqualified and not overqualified
oq = train[train['overqualified'] == 1]
not_oq = train[train['overqualified'] == 0]

# Look at them
print("Overqualified count:", len(oq))
print("Not overqualified count:", len(not_oq))

Overqualified count: 2964
Not overqualified count: 4745

In [21]:
oq.head(10)

,id,CERTLEVP,PGMCIPAP,PGM_P034,PGM_P036,PGM_280A,PGM_280B,PGM_280C,PGM_280F,PGM_P401,...,GRADAGEP,GENDER2,CTZSHIPP,VISBMINP,DDIS_FL,PAR1GRD,PAR2GRD,BEF_P140,BEF_160,overqualified
5,12289,3.0,5.0,1.0,6.0,2.0,2.0,1.0,2.0,9.0,...,3.0,1.0,9.0,1.0,Without disability,6.0,1.0,1.0,6.0,1
6,2694,2.0,2.0,1.0,6.0,2.0,2.0,2.0,9.0,2.0,...,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,5.0,1
8,12041,3.0,1.0,2.0,NaN,2.0,2.0,2.0,1.0,3.0,...,NaN,2.0,1.0,2.0,1.0,1.0,1.0,1.0,6.0,1
11,5322,2.0,5.0,1.0,6.0,2.0,1.0,2.0,6.0,2.0,...,1.0,2.0,1.0,9.0,1.0,1.0,1.0,3.0,6.0,1
17,10647,1.0,9.0,1.0,6.0,2.0,6.0,2.0,1.0,2.0,...,1.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,6.0,1
19,11444,3.0,9.0,1.0,6.0,2.0,2.0,6.0,1.0,1.0,...,3.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,6.0,1
20,11226,1.0,10.0,1.0,6.0,2.0,NaN,2.0,9.0,1.0,...,2.0,1.0,1.0,2.0,2.0,NaN,9.0,3.0,6.0,1
21,1273,2.0,6.0,1.0,6.0,2.0,2.0,6.0,NaN,1.0,...,7.0,2.0,9.0,1.0,2.0,3.0,NaN,3.0,2.0,1
23,31,4.0,5.0,1.0,6.0,2.0,NaN,2.0,1.0,2.0,...,1.0,1.0,1.0,2.0,Without disability,1.0,1.0,3.0,6.0,1
24,10225,1.0,4.0,1.0,6.0,2.0,2.0,2.0,1.0,NaN,...,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3.0,NaN,1

In [22]:
not_oq.head(10)

,id,CERTLEVP,PGMCIPAP,PGM_P034,PGM_P036,PGM_280A,PGM_280B,PGM_280C,PGM_280F,PGM_P401,...,GRADAGEP,GENDER2,CTZSHIPP,VISBMINP,DDIS_FL,PAR1GRD,PAR2GRD,BEF_P140,BEF_160,overqualified
0,187,1.0,4.0,1.0,6.0,2.0,1.0,9.0,2.0,NaN,...,1.0,2.0,2.0,1.0,2.0,3.0,9.0,3.0,4.0,0
1,5343,2.0,5.0,1.0,6.0,2.0,6.0,2.0,9.0,2.0,...,1.0,2.0,1.0,2.0,1.0,3.0,6.0,3.0,6.0,0
2,7011,2.0,99.0,1.0,6.0,2.0,2.0,2.0,1.0,1.0,...,1.0,2.0,2.0,1.0,2.0,NaN,2.0,3.0,3.0,0
3,1519,1.0,7.0,1.0,6.0,2.0,2.0,2.0,1.0,1.0,...,4.0,9.0,2.0,2.0,NaN,6.0,3.0,1.0,NaN,0
4,6770,2.0,5.0,9.0,1.0,2.0,9.0,2.0,1.0,2.0,...,1.0,NaN,1.0,2.0,1.0,6.0,6.0,3.0,3.0,0
7,9483,9.0,NaN,9.0,6.0,2.0,1.0,1.0,2.0,1.0,...,3.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,6.0,0
9,12283,1.0,8.0,NaN,6.0,6.0,2.0,2.0,1.0,1.0,...,1.0,1.0,1.0,2.0,2.0,3.0,2.0,3.0,4.0,0
10,12230,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,...,1.0,NaN,2.0,1.0,2.0,9.0,1.0,3.0,4.0,0
12,5214,2.0,4.0,1.0,6.0,2.0,2.0,2.0,9.0,2.0,...,NaN,1.0,1.0,2.0,1.0,2.0,1.0,1.0,5.0,0
13,2764,1.0,99.0,1.0,6.0,2.0,2.0,2.0,1.0,2.0,...,1.0,2.0,NaN,2.0,1.0,9.0,2.0,1.0,6.0,0